### ISSUE TITLE
The target server failed to respond

### ISSUE THREAD

**Issue by yhdelgado** [yasserg/crawler4j#112]
Hi,
I am using crawler4J 4.2 for crawling PDF files from several sites. Today, I got the following message when I try to run the crawler over http://rcf.fisica.uh.cu site. Is there any way to resolve this issue? This is the complete log from console:

Executing: java -cp sdlcrawler-1.0-SNAPSHOT.jar cu.uci.sdlcrawler.PdfCrawlController
2016/01/22 12:02:41
Crawl storage folder: root
Resumable crawling: false
Max depth of crawl: 4
Max pages to fetch: -1
User agent string: sdlcrawler
Include https pages: true
Include binary content: true
Max connections per host: 100
Max total connections: 100
Socket timeout: 0
Max total connections: 100
Max outgoing links to follow: 10000
Max download size: 5242880
Should follow redirects?: true
Proxy host: localhost
Proxy port: 3128
Proxy username: myuser
Proxy password: mypass

2016-01-22 12:02:42 INFO  TLDList:66 - Obtained 6791 TLD from packaged file tld-names.txt
2016-01-22 12:02:42 INFO  CrawlController:122 - Deleted contents of: root/frontier ( as you have configured resumable crawling to false )
2016-01-22 12:02:42 INFO  CrawlController:230 - Crawler 1 started
2016-01-22 12:02:42 INFO  CrawlController:230 - Crawler 2 started
2016-01-22 12:02:42 INFO  CrawlController:230 - Crawler 3 started
2016-01-22 12:02:42 INFO  CrawlController:230 - Crawler 4 started
2016-01-22 12:02:42 INFO  CrawlController:230 - Crawler 5 started
2016-01-22 12:02:42 INFO  RetryExec:96 - I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:3128->http://rcf.fisica.uh.cu:80: The target server failed to respond
2016-01-22 12:02:42 INFO  RetryExec:112 - Retrying request to {}->http://localhost:3128->http://rcf.fisica.uh.cu:80
2016-01-22 12:02:42 WARN  WebCrawler:412 - Unhandled exception while fetching http://rcf.fisica.uh.cu/: null
2016-01-22 12:02:42 INFO  WebCrawler:357 - Stacktrace: 
java.lang.NullPointerException
    at cu.uci.sdlcrawler.PdfCrawler.shouldVisit(PdfCrawler.java:69)
    at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:357)
    at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:274)
    at java.lang.Thread.run(Thread.java:745)
2016-01-22 12:02:52 INFO  CrawlController:269 - It looks like no thread is working, waiting for 10 seconds to make sure...
2016-01-22 12:03:02 INFO  CrawlController:285 - No thread is working and no more URLs are in queue waiting for another 10 seconds to make sure...
2016-01-22 12:03:12 INFO  CrawlController:295 - All of the crawlers are stopped. Finishing the process...
2016-01-22 12:03:12 INFO  CrawlController:303 - Waiting for 10 seconds before final clean up...
2016/01/22 12:03:22
Total time:41007
 === Finished successfully at vie ene 22 12:03:22 CST 2016 ===

**Comment by s17t** [comment]
The error is quite clear: the HTTP client could not connect to the server. Hope you solve the problem. I will close, this ticket is one year old.
