### ISSUE TITLE
HTTP Content-Type is optional, missing causing NPEs

### ISSUE THREAD

**Issue by cmacdonald** [yasserg/crawler4j#138]
curl -I http://eur-lex.europa.eu/robots.txt
```
HTTP/1.1 200 OK
Date: Wed, 01 Jun 2016 10:31:35 GMT
Content-Length: 4205
Set-Cookie: ELX_SESSIONID=3W4LhLilGmy1dw6EPaR337tDfQrQMtGIG5K6lpsR9mJja_vtzb3R!-338472602; path=/; HttpOnly
Server: Europa
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
```

This has no content-type, but the HTTP standard only mandates that it SHOULD be present. This raises as an error in 2 places:

```
java.lang.NullPointerException: null
        at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:387) [crawler4j-4.3-SNAPSHOT.jar:na]
        at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:281) [crawler4j-4.3-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
```

and 
```
java.lang.NullPointerException: null
        at edu.uci.ics.crawler4j.robotstxt.RobotstxtServer.fetchDirectives(RobotstxtServer.java:124) [crawler4j-4.3-SNAPSHOT.jar:na]
        at edu.uci.ics.crawler4j.robotstxt.RobotstxtServer.getDirectives(RobotstxtServer.java:99) [crawler4j-4.3-SNAPSHOT.jar:na]
        at edu.uci.ics.crawler4j.robotstxt.RobotstxtServer.allows(RobotstxtServer.java:69) [crawler4j-4.3-SNAPSHOT.jar:na]
        at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:422) [crawler4j-4.3-SNAPSHOT.jar:na]
        at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:281) [crawler4j-4.3-SNAPSHOT.jar:na]
```

**Comment by bgoldowsky** [comment]
+1 

I am seeing the same thing, and I want to include error output in case there are real problems, so the full stacktrace ends up getting into my report output.

At the most it should be treated as a logger.warn(...) like having an incorrect content type is.

**Comment by cmacdonald** [comment]
My diff is here:
https://github.com/yasserg/crawler4j/commit/9ff519de2b9b646e23232a8ede940c05b07171cb

**Comment by cmacdonald** [comment]
https://github.com/yasserg/crawler4j/pull/151 has been merged.
