### ISSUE TITLE
Log_File_Not_Found error when crawling

### ISSUE THREAD

**Issue by psushruth** [yasserg/crawler4j#140]
Keep hitting this exception using crawler4j version 4.2

2016-05-31 18:41:22,138 - [ERROR] - from edu.uci.ics.crawler4j.frontier.Frontier in Crawler 5
Error while getting next urls
com.sleepycat.je.EnvironmentFailureException: (JE 5.0.73) Environment must be closed, caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous except
ion: (JE 5.0.73) /usr/share/marketmuse/solrData/crawler4j/2486/frontier fetchTarget of 0x0/0x93bd7a parent IN=1043 IN class=com.sleepycat.je.tree.BIN lastFullVersion=0x3/0x52f99a lastLogged
Version=0x3/0x52f99a parent.getDirty()=false state=0 LOG_FILE_NOT_FOUND: Log file missing, log is likely invalid. Environment is invalid and must be closed.
        at com.sleepycat.je.EnvironmentFailureException.wrapSelf(EnvironmentFailureException.java:196)
        at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1512)
        at com.sleepycat.je.Environment.checkEnv(Environment.java:2185)
        at com.sleepycat.je.Environment.beginTransactionInternal(Environment.java:1313)
        at com.sleepycat.je.Environment.beginTransaction(Environment.java:1284)
        at edu.uci.ics.crawler4j.frontier.WorkQueues.beginTransaction(WorkQueues.java:59)
        at edu.uci.ics.crawler4j.frontier.WorkQueues.get(WorkQueues.java:77)
        at edu.uci.ics.crawler4j.frontier.Frontier.getNextURLs(Frontier.java:132)
        at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:259)
        at marketmuse.web.Crawler.run(Crawler.scala:96)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 5.0.73) /usr/share/marketmuse/solrData/crawler4j/2486/frontier fetchTarget of
 0x0/0x93bd7a parent IN=1043 IN class=com.sleepycat.je.tree.BIN lastFullVersion=0x3/0x52f99a lastLoggedVersion=0x3/0x52f99a parent.getDirty()=false state=0 LOG_FILE_NOT_FOUND: Log file miss
ing, log is likely invalid. Environment is invalid and must be closed.
        at com.sleepycat.je.tree.IN.fetchTarget(IN.java:1429)
        at com.sleepycat.je.tree.BIN.fetchTarget(BIN.java:1251)
        at com.sleepycat.je.dbi.CursorImpl.fetchCurrent(CursorImpl.java:2261)
        at com.sleepycat.je.dbi.CursorImpl.getCurrentAlreadyLatched(CursorImpl.java:1466)
        at com.sleepycat.je.dbi.CursorImpl.getNext(CursorImpl.java:1593)
        at com.sleepycat.je.cleaner.UtilizationProfile.getObsoleteDetail(UtilizationProfile.java:632)
        at com.sleepycat.je.cleaner.FileProcessor.processFile(FileProcessor.java:439)
        at com.sleepycat.je.cleaner.FileProcessor.doClean(FileProcessor.java:289)
        at com.sleepycat.je.cleaner.FileProcessor.onWakeup(FileProcessor.java:148)
        at com.sleepycat.je.utilint.DaemonThread.run(DaemonThread.java:163)
        ... 1 common frames omitted
Caused by: java.io.FileNotFoundException: /usr/share/marketmuse/solrData/crawler4j/2486/frontier/00000000.jdb (No such file or directory)
        at java.io.RandomAccessFile.open(Native Method)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
        at com.sleepycat.je.log.FileManager$DefaultRandomAccessFile.<init>(FileManager.java:3209)
        at com.sleepycat.je.log.FileManager$6.createFile(FileManager.java:3237)
        at com.sleepycat.je.log.FileManager.openFileHandle(FileManager.java:1280)
        at com.sleepycat.je.log.FileManager.getFileHandle(FileManager.java:1152)
        at com.sleepycat.je.log.LogManager.getLogSource(LogManager.java:1141)
        at com.sleepycat.je.log.LogManager.getLogEntry(LogManager.java:845)
        at com.sleepycat.je.log.LogManager.getLogEntryAllowInvisibleAtRecovery(LogManager.java:809)
        at com.sleepycat.je.tree.IN.fetchTarget(IN.java:1412)
        ... 10 common frames omitted

Is this an issue with the sleepycat version used with crawler4j? This happens once in a while.

**Comment by Chaiavi** [comment]
My guess would be that the place where you put your log files gets deleted
from time to time externally thus causing the crawler to break

 /usr/share/marketmuse/solrData/crawler4j/2486/frontier/00000000.jdb

**Comment by psushruth** [comment]
@Chaiavi looks like the underneath sleepycat library has issues which is why this gets deleted.In our case there is no external process which can delete this.

**Comment by Chaiavi** [comment]
I am sorry but you might be right.

Our internal db had issues in the past and the BerkleyDB isn't perfect nor
recently updated

While debugging this issue, pay attention to the place where we close the
db connection (xx.close() for example frontier.close() )

I hope you are wrong so this bug can be fixed

Please keep us updated here

**Comment by psushruth** [comment]
@Chaiavi what if we upgrade to the 4.3-SNAPSHOT version?

**Comment by Chaiavi** [comment]
I don't think there was a fix to a bug like that in the 4.3 snapshot

**Comment by sthmhn** [comment]
Hi,
Me too getting similar error in Berkley db  . Is there any option to delete the cursor reference of that particular key.
com.sleepycat.je.DatabaseException: (JE 3.2.23) fetchTarget of 0x5d628/0x231884 parent IN=239290366 lastFullVersion=0x6a956/0x821dc1 parent.getDirty()=false state=0 com.sleepycat.je.log.LogFileNotFoundException: (JE 3.2.23) 0x5d628/0x231884 (JE 3.2.23) Couldn't open file /dnbusr2/dnb-services/company-service/db.full/identitydatadb/snapshot-201803182000/0005d628.jdb: /dnbusr2/dnb-services/company-service/db.full/identitydatadb/snapshot-201803182000/0005d628.jdb (No such file or directory)
