### ISSUE TITLE
Authentication not working with Crawler4j

### ISSUE THREAD

**Issue by abhinkraj7** [yasserg/crawler4j#142]
I tried to set up a crawler project. But the form authentication or basic authentication is not at all working. what changes I need to incorporate with my java class.

public static void main(String[] args) throws Exception {
        CrawlConfig config = new CrawlConfig();
         String frontier = "/tmp/webCrawler/tmp_" + System.currentTimeMillis();
         config.setCrawlStorageFolder(frontier);
         PageFetcher pageFetcher = new PageFetcher(config);
         RobotstxtConfig robotstxtConfig = new RobotstxtConfig();
         RobotstxtServer robotstxtServer = new RobotstxtServer(robotstxtConfig,pageFetcher);
         AuthInfo authInfo2 = new BasicAuthInfo("admin", "admin", host);
        config.addAuthInfo(authInfo2);
        PageFetcher pf = new PageFetcher(config);
        CrawlController ctrl = new CrawlController(config, pf, robotstxtServer);
        ctrl.addSeed(+host+"/index.html");
        ctrl.startNonBlocking(CustomWebCrawler.class, 5);

Create an another class which extends the WebCrawler class from Crawler4j.

Kindly provide a solution or a document to refer.

**Comment by Chaiavi** [comment]
You say that the auth doesn't work.

There are several types of authentication, are you sure that you need to
use the *basic* auth ?
What is the exception you see when the auth fails ?

**Comment by abhinkraj7** [comment]
15:08:01 INFO  [main] - [PageFetcher]- FORM authentication for: /login.html
15:08:02 DEBUG [main] - [PageFetcher]- Successfully Logged in with user: root to: IDRAC
15:08:02 INFO  [main] - [PageFetcher]- BASIC authentication for: /login.html
15:08:02 DEBUG [main] - [CrawlController]- Created folder: D:\tmp\webCrawler\tmp_1466674681139
15:08:02 INFO  [main] - [TLDList]- Obtained 6791 TLD from packaged file tld-names.txt
15:08:02 DEBUG [main] - [CrawlController]- Created folder: D:\tmp\webCrawler\tmp_1466674681139\frontier
15:08:02 DEBUG [main] - [IO]- Deleting content of: D:\tmp\webCrawler\tmp_1466674681139\frontier
15:08:02 INFO  [main] - [CrawlController]- Deleted contents of: \tmp\webCrawler\tmp_1466674681139\frontier ( as you have configured resumable crawling to false )
15:08:02 DEBUG [main] - [RobotstxtServer]- Can't read this robots.txt:  https://IDRAC/robots.txt  as it's status code is 404
15:08:02 INFO  [main] - [CrawlController]- Crawler 1 started
15:08:02 INFO  [main] - [CrawlController]- Crawler 2 started
15:08:02 INFO  [main] - [CrawlController]- Crawler 3 started
15:08:02 INFO  [main] - [CrawlController]- Crawler 4 started
15:08:02 INFO  [main] - [CrawlController]- Crawler 5 started
15:08:02 WARN  [Crawler 1] - [WebCrawler]- Unhandled exception while fetching https://IDRAC/index.html: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
15:08:02 INFO  [Crawler 1] - [WebCrawler]- Stacktrace: 
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.7.0_17]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1886) ~[na:1.7.0_17]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276) ~[na:1.7.0_17]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270) ~[na:1.7.0_17]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1341) ~[na:1.7.0_17]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:153) ~[na:1.7.0_17]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868) ~[na:1.7.0_17]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:804) ~[na:1.7.0_17]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016) ~[na:1.7.0_17]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312) ~[na:1.7.0_17]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339) ~[na:1.7.0_17]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323) ~[na:1.7.0_17]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:395) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:354) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.4.jar:4.4]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[httpclient-4.4.jar:4.4]
	at edu.uci.ics.crawler4j.fetcher.PageFetcher.fetchPage(PageFetcher.java:237) ~[classes/:na]
	at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:323) [classes/:na]
	at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:278) [classes/:na]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_17]
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385) ~[na:1.7.0_17]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[na:1.7.0_17]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.7.0_17]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326) ~[na:1.7.0_17]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) ~[na:1.7.0_17]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126) ~[na:1.7.0_17]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1323) ~[na:1.7.0_17]
	... 23 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196) ~[na:1.7.0_17]
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268) ~[na:1.7.0_17]
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380) ~[na:1.7.0_17]
	... 29 common frames omitted

-----------------------------------
Class1
public class CustomController {

	public static void main(String[] args) throws Exception {

		// Create the configuration
		CrawlConfig config = new CrawlConfig();
		String frontier = "/tmp/webCrawler/tmp_" + System.currentTimeMillis();
		config.setCrawlStorageFolder(frontier);
		String userName = "root";
		String password = "calpine";
		String urlLogin = "https://IDRAC/login.html";
		String nameUsername = "username";
		String namePassword = "password";
		AuthInfo authInfo1 = new FormAuthInfo(userName,password, urlLogin,nameUsername,namePassword );
		config.addAuthInfo(authInfo1);

		AuthInfo authInfo2 = new BasicAuthInfo(userName, password, urlLogin);
		config.addAuthInfo(authInfo2);
		config.setMaxDepthOfCrawling(-1);

		PageFetcher pageFetcher = new PageFetcher(config);
		RobotstxtConfig robotstxtConfig = new RobotstxtConfig();
		RobotstxtServer robotstxtServer = new RobotstxtServer(robotstxtConfig,
				pageFetcher);
		CrawlController controller = new CrawlController(config, pageFetcher,
				robotstxtServer);

		controller.addSeed("https://IDRAC/index.html");

		controller.start(CustomWebCrawler.class, 5);
		controller.shutdown();
-----------------------------
Class 2
public class CustomWebCrawler  extends WebCrawler{

	private final static Pattern FILTERS = Pattern.compile(".*(\\.(css|js|gif|jpg"
            + "|png|mp3|mp3|zip|gz))$");
	@Override
    public boolean shouldVisit(Page referringPage, WebURL url) {
		
        String href = url.getURL().toLowerCase();
       // return !FILTERS.matcher(href).matches() && href.startsWith("http://www.ics.uci.edu/");
        return true;
    }

    /**
     * This function is called when a page is fetched and ready
     * to be processed by your program.
     */
    @Override
    public void visit(Page page) {
        String url = page.getWebURL().getURL();
        System.out.println("URL: " + url);

        if (page.getParseData() instanceof HtmlParseData) {
            HtmlParseData htmlParseData = (HtmlParseData) page.getParseData();
            String text = htmlParseData.getText();
            String html = htmlParseData.getHtml();
            Set<WebURL> links = htmlParseData.getOutgoingUrls();

            System.out.println("Text length: " + text.length());
            System.out.println("Html length: " + html.length());
            System.out.println("Number of outgoing links: " + links.size());
        }
   }
}

**Comment by Chaiavi** [comment]
Is https://IDRAC/login.html <https://idrac/login.html>
A valid URL from your computer ?

When you put it in a browser (from the same computer which runs crawler4j)
does it find a target web page ?

**Comment by abhinkraj7** [comment]
The original url is https://192.168.3.999/login.html. Due to security issues I mentioned "IDRAC" instead of 192.168.3.999(Still this not correct IP).I'm able to login using browser.

**Comment by Chaiavi** [comment]
Ok, I understand.


I am not sure about the problem, maybe this will help?
http://stackoverflow.com/questions/9619030/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatore

**Comment by abhinkraj7** [comment]
Okay. Let me try it.
I'm also trying this
http://stackoverflow.com/questions/24658634/crawler4j-not-working-for-https-urls

**Comment by Chaiavi** [comment]
I don't think the solution on stackoverflow will help


I have integrated code like that into crawler4j a while back.

I think after that question was answered, so it is an old question
referring an old version of crawler4j, nowdays, it already contains that
code

**Comment by abhinkraj7** [comment]
yes, classes are deprecated.

**Comment by magz99** [comment]
Hello,

I'm wondering if we're having the same issue: I get a certificate error when I use BasicAuth along with https.

From what I can see in PageFetcher.java, the `httpClient` variable gets rebuilt when `doBasicLogin()` is executed, so the line:

```
SSLConnectionSocketFactory sslsf =
                    new SniSSLConnectionSocketFactory(sslContext, NoopHostnameVerifier.INSTANCE);
```

that was done for the initial httpClient var seems to get overridden by default values now. From what I can tell while debugging, `verifyHostname` is not the `NoopHostnameVerifier`.

Below is my error (I've edited it for privacy reasons)

```
10:33:16.203 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory - Starting handshake
.....
10:33:16.558 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory -  peer principal: CN= validValue, OU=validValue, OU="validValue", OU=validValue, O= validValue, STREET="validValue", L= validValue, ST= validValue, OID.2.5.4.17= validValue, C= validValue
10:33:16.558 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory -  peer alternative names: [someothersite.com, yet.anothersite.com]
10:33:16.558 [main] DEBUG org.apache.http.conn.ssl.SSLConnectionSocketFactory -  issuer principal: CN=COMODO RSA Organization Validation Secure Server CA, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB
10:33:16.562 [main] DEBUG org.apache.http.conn.ssl.DefaultHostnameVerifier - Certificate for < mysecuresite.com > doesn't match any of the subject alternative names: [someothersite.com, www.yetanothersite.com]
javax.net.ssl.SSLPeerUnverifiedException: Certificate for <mysecuresite.com> doesn't match any of the subject alternative names: [someothersite.com, www.yetanothersite.com]
    at org.apache.http.conn.ssl.DefaultHostnameVerifier.matchDNSName(DefaultHostnameVerifier.java:177)
    at org.apache.http.conn.ssl.DefaultHostnameVerifier.verify(DefaultHostnameVerifier.java:122)
    at org.apache.http.conn.ssl.DefaultHostnameVerifier.verify(DefaultHostnameVerifier.java:99)
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:463)
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:397)
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
    at edu.uci.ics.crawler4j.fetcher.PageFetcher.fetchPage(PageFetcher.java:256)
    at edu.uci.ics.crawler4j.robotstxt.RobotstxtServer.fetchDirectives(RobotstxtServer.java:108)
    at edu.uci.ics.crawler4j.robotstxt.RobotstxtServer.allows(RobotstxtServer.java:86)
    at edu.uci.ics.crawler4j.crawler.CrawlController.addSeed(CrawlController.java:440)
    at edu.uci.ics.crawler4j.crawler.CrawlController.addSeed(CrawlController.java:394)
    at axe_tool_java.CrawlerController.main(CrawlerController.java:305)
    at axe_tool_java.CrawlerController.main(CrawlerController.java:206)
10:33:16.564 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Shutdown connection
10:33:16.564 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection discarded
```


Thanks!
