### ISSUE TITLE
SSLException: DH key size must be multiple of 64, and can only range from 512 to 2048 (inclusive)

### ISSUE THREAD

**Issue by rzo1** [yasserg/crawler4j#238]
**System:** Windows 10 LTSB, Oracle JDK8 (latest update)
**Page:** https://www.in-form.de/
**Version:** latest master-branch version

**Related:** https://stackoverflow.com/questions/36298394/java-invalidalgorithmparameterexception-prime-size-must-be-multiple-of-64

Using a custom `Provider` such as the  `BountyCastleProvider` will work fine in generating this DH keypairs of size 4096.

Maybe we can implement a `config`-Option for that?

 ```
09:38:56 WARN  [Crawler 1] - [WebCrawler]- Unhandled exception while fetching https://www.in-form.de/: java.lang.RuntimeException: Could not generate DH keypair
09:38:56 INFO  [Crawler 1] - [WebCrawler]- Stacktrace: 
javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at edu.uci.ics.crawler4j.fetcher.SniSSLConnectionSocketFactory.createLayeredSocket(SniSSLConnectionSocketFactory.java:43)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at edu.uci.ics.crawler4j.fetcher.SniPoolingHttpClientConnectionManager.connect(SniPoolingHttpClientConnectionManager.java:43)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at edu.uci.ics.crawler4j.fetcher.PageFetcher.fetchPage(PageFetcher.java:256)
	at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:366)
	at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Could not generate DH keypair
	at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:142)
	at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:114)
	at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:711)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:268)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	... 19 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: DH key size must be multiple of 64, and can only range from 512 to 2048 (inclusive). The specific key size 4096 is not supported
	at com.sun.crypto.provider.DHKeyPairGenerator.initialize(DHKeyPairGenerator.java:128)
	at java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:674)
	at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:128)
	... 27 common frames omitted
```

**Comment by rzo1** [comment]
This issue is related to Oracle JDK and the export policies by the US government.

Corresponding unlimited JCE-files can be found here: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
