### ISSUE TITLE
Unhandled TIKA exception: "java.lang.NoClassDefFoundError"

### ISSUE THREAD

**Issue by LSmyrnaios** [yasserg/crawler4j#311]
Hi,
I updated Crawler4j to version 4.4.0 and while running it I came upon the following exception.

```
Exception in thread "Crawler 1" java.lang.NoClassDefFoundError: org/apache/cxf/jaxrs/ext/multipart/ContentDisposition
	at org.apache.tika.parser.journal.GrobidRESTParser.parse(GrobidRESTParser.java:73)
	at org.apache.tika.parser.journal.JournalParser.parse(JournalParser.java:60)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:135)
	at edu.uci.ics.crawler4j.parser.BinaryParseData.setBinaryContent(BinaryParseData.java:70)
	at edu.uci.ics.crawler4j.parser.Parser.parse(Parser.java:56)
	at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:472)
	at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:306)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by s17t** [comment]
Is this (and #312) reproducible within your project ( https://github.com/LSmyrnaios/DocUrlsRetriever ) ?

**Comment by LSmyrnaios** [comment]
Yes they are. Although I haven't officially pushed the update of Crawler4j's dependency there yet.

**Comment by LSmyrnaios** [comment]
Maybe the following LOG-message is more helpful:

```
Mar 28, 2018 5:35:43 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
Exception in thread "Crawler 1" java.lang.NoClassDefFoundError: org/apache/cxf/jaxrs/ext/multipart/ContentDisposition
	at org.apache.tika.parser.journal.GrobidRESTParser.parse(GrobidRESTParser.java:73)
	at org.apache.tika.parser.journal.JournalParser.parse(JournalParser.java:60)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:135)
	at edu.uci.ics.crawler4j.parser.BinaryParseData.setBinaryContent(BinaryParseData.java:70)
	at edu.uci.ics.crawler4j.parser.Parser.parse(Parser.java:56)
	at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:472)
	at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:306)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.cxf.jaxrs.ext.multipart.ContentDisposition
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
```

**Comment by s17t** [comment]
Do you have a specific url where this happens ?

**Comment by LSmyrnaios** [comment]
Yes, the following is such an example:
http://centaur.reading.ac.uk/68362/8/BJN%20v3%20submitted.pdf

**Comment by LSmyrnaios** [comment]
About TIKA's initialization warning: `WARNING: org.xerial's sqlite-jdbc is not loaded.`
I  added the following dependency in my pom.xml (this wasn't necessary in Crawler4j v4.3)
This warning is not showing now, but, the exception is still there.

```
  <!-- https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc -->
  <dependency>
    <groupId>org.xerial</groupId>
    <artifactId>sqlite-jdbc</artifactId>
    <version>3.21.0.1</version>
  </dependency>
```

**Comment by rzo1** [comment]
We currently exclude the following TIKA dependencies:

```
<exclusions>
			<exclusion>
				<groupId>org.apache.poi</groupId>
				<artifactId>poi</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.poi</groupId>
				<artifactId>poi-ooxml</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.poi</groupId>
				<artifactId>poi-scratchpad</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.poi</groupId>
				<artifactId>poi-ooxml</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.poi</groupId>
				<artifactId>poi-ooxml-schemas</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.pdfbox</groupId>
				<artifactId>pdfbox</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.pdfbox</groupId>
				<artifactId>pdfbox-tools</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.pdfbox</groupId>
				<artifactId>jempbox</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.tallison</groupId>
				<artifactId>jmatio</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.healthmarketscience.jackcess</groupId>
				<artifactId>jackcess</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.healthmarketscience.jackcess</groupId>
				<artifactId>jackcess-encrypt</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.tukaani</groupId>
				<artifactId>xz</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.github.junrar</groupId>
				<artifactId>junrar</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.opennlp</groupId>
				<artifactId>opennlp-tools</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.sis.core</groupId>
				<artifactId>sis-utility</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.sis.storage</groupId>
				<artifactId>sis-netcdf</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.sis.core</groupId>
				<artifactId>sis-metadata</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.opengis</groupId>
				<artifactId>geoapi</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.pff</groupId>
				<artifactId>java-libpst</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.rometools</groupId>
				<artifactId>rome</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.json</groupId>
				<artifactId>json</artifactId>
			</exclusion>
			<exclusion>
				<groupId>edu.ucar</groupId>
				<artifactId>netcdf4</artifactId>
			</exclusion>
			<exclusion>
				<groupId>edu.ucar</groupId>
				<artifactId>grib</artifactId>
			</exclusion>
			<exclusion>
				<groupId>edu.ucar</groupId>
				<artifactId>cdm</artifactId>
			</exclusion>
			<exclusion>
				<groupId>edu.ucar</groupId>
				<artifactId>httpservices</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.gagravarr</groupId>
				<artifactId>vorbis-java-tika</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.gagravarr</groupId>
				<artifactId>vorbis-java-core</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.ow2.asm</groupId>
				<artifactId>asm</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.googlecode.mp4parser</groupId>
				<artifactId>isoparser</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.drewnoakes</groupId>
				<artifactId>metadata-extractor</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-csv</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-exec</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-compress</artifactId>
			</exclusion>
			<exclusion>
				<groupId>commons-codec</groupId>
				<artifactId>commons-codec</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.googlecode.json-simple</groupId>
				<artifactId>json-simple</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.google.code.gson</groupId>
				<artifactId>gson</artifactId>
			</exclusion>
			<exclusion>
				<groupId>de.l3s.boilerpipe</groupId>
				<artifactId>boilerpipe</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.googlecode.juniversalchardet</groupId>
				<artifactId>juniversalchardet</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.codelibs</groupId>
				<artifactId>jhighlight</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.bouncycastle</groupId>
				<artifactId>bcmail-jdk15on</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.bouncycastle</groupId>
				<artifactId>bcprov-jdk15on</artifactId>
			</exclusion>
			<exclusion>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-rs-client</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-core</artifactId>
			</exclusion>
			<exclusion>
				<groupId>com.tdunning</groupId>
				<artifactId>json</artifactId>
			</exclusion>
			<exclusion>
				<groupId>edu.usc.ir</groupId>
				<artifactId>sentiment-analysis-parser</artifactId>
			</exclusion>
		</exclusions>
```

It could be sufficient, if you add the related dependency (which is needed for your PDF-crawl) to your classpath.

**Comment by s17t** [comment]
Like @rzo1 noted, we exclude some heavy weight tika optional dependencies. You can add them to your project and tika will load and use them. I did a quick test and the pointed PDF is processed without error. Please tell us if you need further support.

**Comment by LSmyrnaios** [comment]
Sorry to respond kind of late, but I had a busy week.
So, I got it running after adding: 
> "cxf-rt-rs-client" & "javax.ws.rs-api"

My crawler now runs properly.
@s17t  there is still a parsing error for the above url but this time because of a problematic connection as I am recieving a `java.net.ConnectException: Connection refused`.
