### ISSUE TITLE
Crawler does not shutdown after calling shutdown on controller

### ISSUE THREAD

**Issue by rockyhalo** [yasserg/crawler4j#327]
### Code Snippet :

CrawlConfig config = new CrawlConfig();
config.setCrawlStorageFolder(ServiceConfiguration.getConfiguration().crawlerTempFolder);
config.setPolitenessDelay(1500);
config.setMaxDepthOfCrawling(1);
config.setMaxPagesToFetch(-1);
config.setIncludeBinaryContentInCrawling(false);
config.setResumableCrawling(false);
config.setIncludeHttpsPages(true);
config.setUserAgentString("Some User Agent");

PageFetcher pageFetcher = new PageFetcher(config);
RobotstxtConfig robotstxtConfig = new RobotstxtConfig();
RobotstxtServer robotstxtServer = new RobotstxtServer(robotstxtConfig, pageFetcher);
controller = new CrawlController(config, pageFetcher, robotstxtServer);
controller.addSeed("https://www.wikipedia.org/");

controller.startNonBlocking(CrawlerManager.class, 1);

### Error Message
ERROR edu.uci.ics.crawler4j.robotstxt.RobotstxtServer - Error occurred while fetching (robots) url: https://sr.wikipedia.org/robots.txt
java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34) ~[httpcore-4.4.6.jar:4.4.6]
	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:189) ~[httpcore-4.4.6.jar:4.4.6]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:257) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.3.jar:4.5.3]
	at edu.uci.ics.crawler4j.fetcher.PageFetcher.fetchPage(PageFetcher.java:264) ~[crawler4j-4.4.0.jar:?]
	at edu.uci.ics.crawler4j.robotstxt.RobotstxtServer.fetchDirectives(RobotstxtServer.java:108) [crawler4j-4.4.0.jar:?]
	at edu.uci.ics.crawler4j.robotstxt.RobotstxtServer.allows(RobotstxtServer.java:86) [crawler4j-4.4.0.jar:?]
	at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:492) [crawler4j-4.4.0.jar:?]
	at edu.uci.ics.crawler4j.crawler.WebCrawler.run(WebCrawler.java:306) [crawler4j-4.4.0.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

**Comment by pgalbraith** [comment]
To clarify, I believe it does shutdown, but not cleanly (i.e. the error above is usually thrown before exiting).

**Comment by checklist** [comment]
Any solutions?

**Comment by pricetheos** [comment]
Same issue
